<div class="page-content">

    <div class="content notch-clear">
        <div class="d-flex py-2">
            <div class="align-self-center me-auto">
                <strong class="text-uppercase opacity-60 font-12">Welcome Back</strong>
                <h1 class="mt-n2 font-27">Events Home 2</h1>
            </div>
            <div class="align-self-center ms-auto">
                <a href="#" class="d-block" data-menu="menu-events"><img src="images/pictures/0s.png" class="img-fluid shadow-xl rounded-circle" width="52"></a>
            </div>
        </div>
    </div>






    <div class="d-flex px-3 pb-3">
        <div class="align-self-center">
            <h4 class="mb-0">Danh sách menu</h4>
            <p class="mt-n1 mb-0">
                Quản lý danh sách menu
            </p>
        </div>
        <div class="align-self-center ms-auto">
            <a href="#" class="font-12">Thêm menu</a>
        </div>
    </div>
    <div >
        <div class="card card-style px-3 pt-1 pb-3">
            <p class="text-uppercase font-700 color-gray-dark font-10 mb-2"></p>
            <div class="d-flex">
                <div class="align-self-center">
                    <h4 class="ps-2 pt-2">MENu 1</h4>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="#" class="btn btn-s rounded-sm text-uppercase font-700 border-gray-dark color-theme">Thêm Món</a>
                </div>
            </div>
            <div class="divider mt-3 mb-3"></div>

            <div class="divider mb-3"></div>
            <div class="row mb-0">
                <div class="col-6">
                    <a href="#" class="btn btn-m btn-border border-green-dark color-green-dark btn-full rounded-sm text-uppercase font-800">Xóa</a>
                </div>
                <div class="col-6">
                    <a href="#" class="btn btn-m bg-green-dark btn-full rounded-sm text-uppercase font-800">Sửa</a>
                </div>
            </div>
        </div>
    </div>



    <div class="d-flex px-3">
        <div class="align-self-center">
            <h4 class="mb-0">Danh sách review</h4>
        </div>
        <div class="align-self-center ms-auto">
            <a href="#" class="font-12">View All</a>
        </div>
    </div>


</div>