<div class="page-content pb-0">
    <div data-card-height="cover" class="card">
        <div class="card-top notch-clear">
            <a href="#" data-back-button class="me-auto icon icon-m" onclick="history.back()"><i class="font-14 fa fa-arrow-left color-white"></i></a>
        </div>
        <div class="card-center text-center">
            <h1 class="center-text mb-5"><i class="fa fa-3x fa-exclamation-triangle color-<?=$code==404?'yellow':'red'?>-dark "></i></h1>
            <h1 class="center-text color-white bolder fa-5x mb-3"><?=$code?></h1>
            <h6 class="center-text color-white font-800 font-14 mb-4"><?=$title?></h6>
        </div>
        <div class="card-overlay bg-black opacity-80"></div>
        <div class="card-overlay-infinite preload-img" data-src="<?= config('view_static') ?>/static/images/pictures/_bg-infinite.jpg"></div>
    </div>
</div>
