<!DOCTYPE HTML>
<html lang="vi">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"/>


    <title>TapLink</title>

    <link rel="stylesheet" type="text/css" href="<?= config('view_static') ?>/static/styles/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?= config('view_static') ?>/static/styles/style.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900,900i|Source+Sans+Pro:300,300i,400,400i,600,600i,700,700i,900,900i&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?= config('view_static') ?>/static/fonts/css/fontawesome-all.min.css">
    <link rel="manifest" href="<?= config('view_static') ?>/static/_manifest.json" data-pwa-version="set_in_manifest_and_pwa_js">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= config('view_static') ?>/static/app/icons/icon-192x192.png">
    <script src="<?= config('view_static') ?>/static/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="<?= config('view_static') ?>/static/plugins/sweetalert/sweetalert.min.js" type="text/javascript"></script>

</head>
<body class="theme-light" data-highlight="highlight-blue" data-gradient="body-default">
<div id="preloader">
    <div class="spinner-border color-highlight" role="status"></div>
</div>
<div id="page">
    <?= $content ?>
</div>
<script type="text/javascript" src="<?= config('view_static') ?>/static/scripts/bootstrap.min.js"></script>
<script type="text/javascript" src="<?= config('view_static') ?>/static/scripts/custom.js"></script>

</body>
