<script src="<?= config('view_static') ?>/static/page/login.js" type="text/javascript"></script>
<input id="option" value="<?= $option ?>" hidden>
<div class="page-content pb-0">
    <div data-card-height="cover" class="card">
        <div class="card-center">
            <div class="ps-5 pe-5">
                <h1 class="color-white text-center font-800 font-40 mb-1">Sign up</h1>
                <h2 class="color-white color-highlight text-center font-12"><?= $mess ?></h2>

                <form method="post" action="<?= url('login') ?>">
                    <div class="input-style input-transparent no-borders has-icon ">
                        <i class="fa fa-phone"></i>
                        <input type="tel" value="<?= $phone ?>" class="form-control" id="phone" name="phone"
                               placeholder="Số điện thoại" required autocomplete="off">
                        <label for="phone" class="color-blue-dark font-10 mt-1">Số điện thoại</label>

                    </div>

                    <div class="input-style input-transparent no-borders has-icon mt-4">
                        <i class="fa fa-lock"></i>
                        <input type="password" class="form-control" id="password" name="password"
                               placeholder="Mật khẩu">
                        <label for="password" class="color-blue-dark font-10 mt-1">Mật khẩu</label>

                    </div>



                    <button type="submit"
                            class=" btn-block back-button btn btn-full btn-m shadow-large rounded-sm text-uppercase font-900 bg-highlight"
                            style="width:100%">Sign up
                    </button>
                </form>
            </div>

        </div>
        <div class="card-overlay bg-black opacity-80"></div>
        <div class="card-overlay-infinite preload-img"
             data-src="<?= config('view_static') ?>/static/images/pictures/_bg-infinite.jpg"></div>
    </div>
</div>
