<div class="page-content pb-0">

    <div class="card" data-card-height="cover" style="height: 619px;">
        <div class="card-top notch-clear">
            <div class="d-flex">
                <a href="#" data-back-button="" class="me-auto icon icon-m"><i class="font-14 fa fa-arrow-left color-theme"></i></a>
                <a href="#" data-toggle-theme="" class="show-on-theme-light ms-auto icon icon-m"><i class="font-12 fa fa-moon color-theme"></i></a>
                <a href="#" data-toggle-theme="" class="show-on-theme-dark ms-auto icon icon-m"><i class="font-12 fa fa-lightbulb color-yellow-dark"></i></a>
            </div>
        </div>
        <div class="card-center">
            <img src="<?= config('view_static') ?>/static/images/undraw/2.svg" width="200" class="mx-auto">
            <h1 class="text-center pt-4">Enter Phone Number</h1>
            <p class="text-center font-12 mt-n2 mb-2">Let's verify your account before we proceed.</p>
            <div class="text-center mb-3 pt-3 pb-2">
                <form action="" style="display: flex; justify-content: center">
                    <input style="width: 250px; height: 50px" type="tel" class="form-control validate-text" id="form4" placeholder="Phone">
                </form>
            </div>
            <a href="#" data-menu="menu-verified" class="btn btn-highlight rounded-sm btn-m bg-green-dark text-uppercase font-700 mt-4 btn-center-xl" style="">Verify</a>
            </p></div>
    </div>

</div>
